name = "pb"
compatibility_date = "2023-01-28"

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*.html", "*.client.js", "*.md", "*.css" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "paste.gaoxu.me"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "341f05be92de41bab67eb59ae90d7a30"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://paste.gaoxu.me"

# url to repo, displayed in index page
REPO = "https://github.com/luoxufeiyan/pastebin-cf-worker"

# url to favicon
FAVICON = "https://projects.luoxufeiyan.com/uploads/pastebin/favicon.ico"

# the name displayed in TOS
TOS_MAINTAINER = "Hugh"

# the email displayed in TOS
TOS_MAIL = "admin@luoxufeiyan.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
